using System.ComponentModel.DataAnnotations;
using Juweirat.Domain.Enums;

namespace Juweirat.Application.DTOs.Folios;

public record FolioDto(
    long Id,
    string Number,
    long UnitId,
    string? Guest,
    string? Nom,
    string? Prenom,
    string? Societe,
    string? Reservataire,
    string Segment,
    int Pax,
    DateOnly Arrival,
    DateOnly Departure,
    int Rate,
    int Heb,
    string TarifTier,
    bool ElecIncluded,
    int PdjParJour,
    int PdjPrix,
    int Debiteur,
    int Dependances,
    int Arrhes,
    int Paid,
    string? PayMode,
    string? FactRecipient,
    string ResaStatus,
    bool CheckedIn,
    bool Closed,
    DateOnly? CheckoutDate,
    string? Note,
    long? FactureId,
    long? ReservationId,
    int Total,
    int Solde,
    int Nights,
    int PdjTot,
    int Avoir,
    int Encaisse
);

public record CreateFolioRequest(
    [Required] long UnitId,
    [Required] DateOnly Arrival,
    [Required] DateOnly Departure,
    string? Guest = null,
    string? Nom = null,
    string? Prenom = null,
    string? Societe = null,
    int Rate = 0,
    int Pax = 1,
    string? Segment = "Direct",
    string? ResaStatus = "Confirmee"
);

public record UpdateFolioRequest(
    long UnitId,
    DateOnly Arrival,
    DateOnly Departure,
    string? Guest,
    string? Nom,
    string? Prenom,
    string? Societe,
    string? Reservataire,
    string? Segment,
    int Pax,
    int Rate,
    int Heb,
    string? TarifTier,
    bool ElecIncluded,
    int PdjParJour,
    int PdjPrix,
    int Debiteur,
    int Dependances,
    int Arrhes,
    int Paid,
    string? PayMode,
    string? FactRecipient,
    string? ResaStatus,
    bool CheckedIn,
    bool Closed,
    DateOnly? CheckoutDate,
    string? Note,
    long? FactureId,
    long? ReservationId
);
