services:
  juweirat-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: juweirat-web
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file: .env.local
    environment:
      - NODE_ENV=production
    networks:
      - juweirat-net

networks:
  juweirat-net:
    driver: bridge
