// <auto-generated />
using System;
using Juweirat.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Juweirat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.Property<long>("AmenitiesId")
                        .HasColumnType("bigint")
                        .HasColumnName("amenitiesId");

                    b.Property<long>("RoomsId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomsId");

                    b.HasKey("AmenitiesId", "RoomsId");

                    b.HasIndex("RoomsId")
                        .HasDatabaseName("iX_roomAmenities_roomsId");

                    b.ToTable("roomAmenities", (string)null);
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Amenity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameEn");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameFr");

                    b.HasKey("Id");

                    b.ToTable("amenities");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text")
                        .HasColumnName("documentNumber");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text")
                        .HasColumnName("documentType");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("Nationality")
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("iX_clients_email")
                        .HasFilter("\"email\" IS NOT NULL");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Cloture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CaHeb")
                        .HasColumnType("integer")
                        .HasColumnName("caHeb");

                    b.Property<int>("CaPdj")
                        .HasColumnType("integer")
                        .HasColumnName("caPdj");

                    b.Property<int>("CaTotal")
                        .HasColumnType("integer")
                        .HasColumnName("caTotal");

                    b.Property<DateOnly>("DateHotel")
                        .HasColumnType("date")
                        .HasColumnName("dateHotel");

                    b.Property<int>("Dispo")
                        .HasColumnType("integer")
                        .HasColumnName("dispo");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executedAt");

                    b.Property<int>("Montant")
                        .HasColumnType("integer")
                        .HasColumnName("montant");

                    b.Property<int>("NbArrivals")
                        .HasColumnType("integer")
                        .HasColumnName("nbArrivals");

                    b.Property<int>("NbDeparts")
                        .HasColumnType("integer")
                        .HasColumnName("nbDeparts");

                    b.Property<int>("NbLignes")
                        .HasColumnType("integer")
                        .HasColumnName("nbLignes");

                    b.Property<int>("NbNoShow")
                        .HasColumnType("integer")
                        .HasColumnName("nbNoShow");

                    b.Property<int>("Occ")
                        .HasColumnType("integer")
                        .HasColumnName("occ");

                    b.Property<decimal>("Occupation")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("occupation");

                    b.Property<int>("Pm")
                        .HasColumnType("integer")
                        .HasColumnName("pm");

                    b.Property<int>("RevPar")
                        .HasColumnType("integer")
                        .HasColumnName("revPar");

                    b.HasKey("Id");

                    b.HasIndex("DateHotel")
                        .IsUnique()
                        .HasDatabaseName("iX_clotures_dateHotel");

                    b.ToTable("clotures");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Debtor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("dueDate");

                    b.Property<long?>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folioId");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Paid")
                        .HasColumnType("integer")
                        .HasColumnName("paid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("FolioId")
                        .HasDatabaseName("iX_debtors_folioId");

                    b.ToTable("debtors");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Facture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Corrections")
                        .HasColumnType("integer")
                        .HasColumnName("corrections");

                    b.Property<DateOnly?>("CorrigeeLe")
                        .HasColumnType("date")
                        .HasColumnName("corrigeeLe");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folioId");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<int>("PrintCount")
                        .HasColumnType("integer")
                        .HasColumnName("printCount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("FolioId")
                        .IsUnique()
                        .HasDatabaseName("iX_factures_folioId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("iX_factures_number");

                    b.ToTable("factures");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Folio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Arrhes")
                        .HasColumnType("integer")
                        .HasColumnName("arrhes");

                    b.Property<DateOnly>("Arrival")
                        .HasColumnType("date")
                        .HasColumnName("arrival");

                    b.Property<string>("CardExpiry")
                        .HasColumnType("text")
                        .HasColumnName("cardExpiry");

                    b.Property<string>("CardHolder")
                        .HasColumnType("text")
                        .HasColumnName("cardHolder");

                    b.Property<string>("CardNumber")
                        .HasColumnType("text")
                        .HasColumnName("cardNumber");

                    b.Property<bool>("CheckedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("checkedIn");

                    b.Property<DateOnly?>("CheckoutDate")
                        .HasColumnType("date")
                        .HasColumnName("checkoutDate");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("Debiteur")
                        .HasColumnType("integer")
                        .HasColumnName("debiteur");

                    b.Property<DateOnly>("Departure")
                        .HasColumnType("date")
                        .HasColumnName("departure");

                    b.Property<int>("Dependances")
                        .HasColumnType("integer")
                        .HasColumnName("dependances");

                    b.Property<bool>("ElecIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("elecIncluded");

                    b.Property<string>("FactRecipient")
                        .HasColumnType("text")
                        .HasColumnName("factRecipient");

                    b.Property<long?>("FactureId")
                        .HasColumnType("bigint")
                        .HasColumnName("factureId");

                    b.Property<string>("Guest")
                        .HasColumnType("text")
                        .HasColumnName("guest");

                    b.Property<int>("Heb")
                        .HasColumnType("integer")
                        .HasColumnName("heb");

                    b.Property<int>("Kwh")
                        .HasColumnType("integer")
                        .HasColumnName("kwh");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<int>("Paid")
                        .HasColumnType("integer")
                        .HasColumnName("paid");

                    b.Property<int>("Pax")
                        .HasColumnType("integer")
                        .HasColumnName("pax");

                    b.Property<string>("PayMode")
                        .HasColumnType("text")
                        .HasColumnName("payMode");

                    b.Property<int>("PdjParJour")
                        .HasColumnType("integer")
                        .HasColumnName("pdjParJour");

                    b.Property<int>("PdjPrix")
                        .HasColumnType("integer")
                        .HasColumnName("pdjPrix");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<int>("Rate")
                        .HasColumnType("integer")
                        .HasColumnName("rate");

                    b.Property<string>("ResaStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resaStatus");

                    b.Property<string>("Reservataire")
                        .HasColumnType("text")
                        .HasColumnName("reservataire");

                    b.Property<long?>("ReservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("reservationId");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment");

                    b.Property<string>("Societe")
                        .HasColumnType("text")
                        .HasColumnName("societe");

                    b.Property<string>("TarifTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tarifTier");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unitId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("iX_folios_number");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("iX_folios_reservationId");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("iX_folios_unitId");

                    b.ToTable("folios");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.HotelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("buildingName");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currencyCode");

                    b.Property<int>("CurrencyDecimals")
                        .HasColumnType("integer")
                        .HasColumnName("currencyDecimals");

                    b.Property<DateOnly>("DateHotel")
                        .HasColumnType("date")
                        .HasColumnName("dateHotel");

                    b.Property<int>("FactureSeq")
                        .HasColumnType("integer")
                        .HasColumnName("factureSeq");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownerName");

                    b.Property<int>("ResaSeq")
                        .HasColumnType("integer")
                        .HasColumnName("resaSeq");

                    b.HasKey("Id");

                    b.ToTable("hotelConfig");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int?>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvedAt");

                    b.Property<string>("Spot")
                        .HasColumnType("text")
                        .HasColumnName("spot");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tech")
                        .HasColumnType("text")
                        .HasColumnName("tech");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unitId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("iX_maintenanceTickets_unitId");

                    b.ToTable("maintenanceTickets");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("XOF")
                        .HasColumnName("currency");

                    b.Property<string>("GatewayReference")
                        .HasColumnType("text")
                        .HasColumnName("gatewayReference");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text")
                        .HasColumnName("gatewayResponse");

                    b.Property<string>("InternalReference")
                        .HasColumnType("text")
                        .HasColumnName("internalReference");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paidAt");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("reservationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("iX_payments_reservationId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Posting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateHotel")
                        .HasColumnType("date")
                        .HasColumnName("dateHotel");

                    b.Property<string>("Famille")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("famille");

                    b.Property<long>("FolioId")
                        .HasColumnType("bigint")
                        .HasColumnName("folioId");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horodatage");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("libelle");

                    b.Property<int>("Montant")
                        .HasColumnType("integer")
                        .HasColumnName("montant");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unitId");

                    b.HasKey("Id");

                    b.HasIndex("FolioId")
                        .HasDatabaseName("iX_postings_folioId");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("iX_postings_unitId");

                    b.ToTable("postings");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Adults")
                        .HasColumnType("integer")
                        .HasColumnName("adults");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellationReason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelledAt");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryId");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date")
                        .HasColumnName("checkInDate");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date")
                        .HasColumnName("checkOutDate");

                    b.Property<int>("Children")
                        .HasColumnType("integer")
                        .HasColumnName("children");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("clientId");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("XOF")
                        .HasColumnName("currency");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text")
                        .HasColumnName("internalNotes");

                    b.Property<int>("Nights")
                        .HasColumnType("integer")
                        .HasColumnName("nights");

                    b.Property<decimal>("PricePerNightSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricePerNightSnapshot");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomId");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("text")
                        .HasColumnName("specialRequests");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalPrice");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("iX_reservations_categoryId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("iX_reservations_clientId");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("iX_reservations_reference");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("iX_reservations_roomId");

                    b.ToTable("reservations", t =>
                        {
                            t.HasCheckConstraint("ck_checkOutAfterCheckIn", "\"checkOutDate\" > \"checkInDate\"");
                        });
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CapacityAdults")
                        .HasColumnType("integer")
                        .HasColumnName("capacityAdults");

                    b.Property<int>("CapacityChildren")
                        .HasColumnType("integer")
                        .HasColumnName("capacityChildren");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("descriptionEn");

                    b.Property<string>("DescriptionFr")
                        .HasColumnType("text")
                        .HasColumnName("descriptionFr");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<bool>("HorsService")
                        .HasColumnType("boolean")
                        .HasColumnName("horsService");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("isFeatured");

                    b.Property<DateOnly?>("LastCleaned")
                        .HasColumnType("date")
                        .HasColumnName("lastCleaned");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameEn");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameFr");

                    b.Property<int>("PlanCol")
                        .HasColumnType("integer")
                        .HasColumnName("planCol");

                    b.Property<int>("PlanRow")
                        .HasColumnType("integer")
                        .HasColumnName("planRow");

                    b.Property<string>("PmsGamme")
                        .HasColumnType("text")
                        .HasColumnName("pmsGamme");

                    b.Property<string>("PmsRoomNo")
                        .HasColumnType("text")
                        .HasColumnName("pmsRoomNo");

                    b.Property<string>("PmsType")
                        .HasColumnType("text")
                        .HasColumnName("pmsType");

                    b.Property<decimal?>("PricePerMonth")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricePerMonth");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricePerNight");

                    b.Property<decimal?>("PricePerWeek")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricePerWeek");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roomNumber");

                    b.Property<decimal?>("SizeSqm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("sizeSqm");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<string>("StatutMenage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Propre")
                        .HasColumnName("statutMenage");

                    b.Property<int>("TarifN15")
                        .HasColumnType("integer")
                        .HasColumnName("tarifN15");

                    b.Property<int>("TarifN30")
                        .HasColumnType("integer")
                        .HasColumnName("tarifN30");

                    b.Property<int>("TarifNuit")
                        .HasColumnType("integer")
                        .HasColumnName("tarifNuit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("iX_rooms_categoryId");

                    b.HasIndex("PmsRoomNo")
                        .IsUnique()
                        .HasDatabaseName("iX_rooms_pmsRoomNo")
                        .HasFilter("\"pmsRoomNo\" IS NOT NULL");

                    b.HasIndex("RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("iX_rooms_roomNumber");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomId");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("iX_roomBlocks_roomId");

                    b.ToTable("roomBlocks", t =>
                        {
                            t.HasCheckConstraint("ck_blockEndAfterStart", "\"endDate\" > \"startDate\"");
                        });
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CapacityAdults")
                        .HasColumnType("integer")
                        .HasColumnName("capacityAdults");

                    b.Property<int>("CapacityChildren")
                        .HasColumnType("integer")
                        .HasColumnName("capacityChildren");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("descriptionEn");

                    b.Property<string>("DescriptionFr")
                        .HasColumnType("text")
                        .HasColumnName("descriptionFr");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameEn");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameFr");

                    b.Property<string>("PmsGamme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pmsGamme");

                    b.Property<string>("PmsType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pmsType");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("TarifN15")
                        .HasColumnType("integer")
                        .HasColumnName("tarifN15");

                    b.Property<int>("TarifN30")
                        .HasColumnType("integer")
                        .HasColumnName("tarifN30");

                    b.Property<int>("TarifNuit")
                        .HasColumnType("integer")
                        .HasColumnName("tarifNuit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("iX_roomCategories_slug");

                    b.ToTable("roomCategories");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AltTextEn")
                        .HasColumnType("text")
                        .HasColumnName("altTextEn");

                    b.Property<string>("AltTextFr")
                        .HasColumnType("text")
                        .HasColumnName("altTextFr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filePath");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("isCover");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("iX_roomImages_roomId");

                    b.ToTable("roomImages");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastLoginAt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("staff")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("iX_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_roomAmenities_Amenities_amenitiesId");

                    b.HasOne("Juweirat.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_roomAmenities_Rooms_roomsId");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Debtor", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Folio", "Folio")
                        .WithMany("Debtors")
                        .HasForeignKey("FolioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_debtors_Folios_folioId");

                    b.Navigation("Folio");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Facture", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Folio", "Folio")
                        .WithOne("Facture")
                        .HasForeignKey("Juweirat.Domain.Entities.Facture", "FolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_factures_Folios_folioId");

                    b.OwnsOne("Juweirat.Domain.Entities.FactureSnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<long>("FactureId");

                            b1.Property<int>("Arrhes");

                            b1.Property<DateOnly?>("Arrival");

                            b1.Property<string>("Client");

                            b1.Property<DateOnly?>("Departure");

                            b1.Property<int>("Nights");

                            b1.Property<int>("Paid");

                            b1.Property<int>("Pax");

                            b1.Property<string>("PayMode");

                            b1.Property<string>("Recipient");

                            b1.Property<string>("Reservataire");

                            b1.Property<string>("Societe");

                            b1.Property<int>("Total");

                            b1.Property<string>("UnitLabel");

                            b1.HasKey("FactureId");

                            b1.ToTable("factures");

                            b1
                                .ToJson("snapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FactureId");

                            b1.OwnsMany("Juweirat.Domain.Entities.FactureSnapshotLine", "Lines", b2 =>
                                {
                                    b2.Property<long>("FactureSnapshotFactureId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Label")
                                        .IsRequired();

                                    b2.Property<int>("Montant");

                                    b2.HasKey("FactureSnapshotFactureId", "__synthesizedOrdinal");

                                    b2.ToTable("factures");

                                    b2.WithOwner()
                                        .HasForeignKey("FactureSnapshotFactureId");
                                });

                            b1.Navigation("Lines");
                        });

                    b.Navigation("Folio");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Folio", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Reservation", "Reservation")
                        .WithOne("Folio")
                        .HasForeignKey("Juweirat.Domain.Entities.Folio", "ReservationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_folios_Reservations_reservationId");

                    b.HasOne("Juweirat.Domain.Entities.Room", "Unit")
                        .WithMany("Folios")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_folios_Rooms_unitId");

                    b.Navigation("Reservation");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Room", "Unit")
                        .WithMany("Tickets")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_maintenanceTickets_Rooms_unitId");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_payments_Reservations_reservationId");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Posting", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Folio", "Folio")
                        .WithMany("Postings")
                        .HasForeignKey("FolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_postings_folios_folioId");

                    b.HasOne("Juweirat.Domain.Entities.Room", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_postings_Rooms_unitId");

                    b.Navigation("Folio");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.RoomCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_reservations_RoomCategories_categoryId");

                    b.HasOne("Juweirat.Domain.Entities.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_reservations_clients_clientId");

                    b.HasOne("Juweirat.Domain.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fK_reservations_Rooms_roomId");

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Room", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.RoomCategory", "Category")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fK_rooms_RoomCategories_categoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomBlock", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Room", "Room")
                        .WithMany("Blocks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_roomBlocks_rooms_roomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomImage", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_roomImages_rooms_roomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ReplyMessage")
                        .HasColumnType("text")
                        .HasColumnName("replyMessage");

                    b.Property<DateTimeOffset?>("RepliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("repliedAt");

                    b.Property<string>("RepliedBy")
                        .HasColumnType("text")
                        .HasColumnName("repliedBy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.ToTable("contactMessages");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Folio", b =>
                {
                    b.Navigation("Debtors");

                    b.Navigation("Facture");

                    b.Navigation("Postings");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Folio");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Room", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Folios");

                    b.Navigation("Images");

                    b.Navigation("Reservations");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomCategory", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
