// <auto-generated />
using System;
using Juweirat.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Juweirat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.Property<long>("AmenitiesId")
                        .HasColumnType("bigint")
                        .HasColumnName("amenitiesId");

                    b.Property<long>("RoomsId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomsId");

                    b.HasKey("AmenitiesId", "RoomsId");

                    b.HasIndex("RoomsId")
                        .HasDatabaseName("iX_roomAmenities_roomsId");

                    b.ToTable("roomAmenities", (string)null);
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Amenity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameEn");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameFr");

                    b.HasKey("Id");

                    b.ToTable("amenities");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text")
                        .HasColumnName("documentNumber");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text")
                        .HasColumnName("documentType");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("Nationality")
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("iX_clients_email")
                        .HasFilter("\"email\" IS NOT NULL");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("XOF")
                        .HasColumnName("currency");

                    b.Property<string>("GatewayReference")
                        .HasColumnType("text")
                        .HasColumnName("gatewayReference");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text")
                        .HasColumnName("gatewayResponse");

                    b.Property<string>("InternalReference")
                        .HasColumnType("text")
                        .HasColumnName("internalReference");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paidAt");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("reservationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("iX_payments_reservationId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Adults")
                        .HasColumnType("integer")
                        .HasColumnName("adults");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellationReason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelledAt");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date")
                        .HasColumnName("checkInDate");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date")
                        .HasColumnName("checkOutDate");

                    b.Property<int>("Children")
                        .HasColumnType("integer")
                        .HasColumnName("children");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("clientId");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("XOF")
                        .HasColumnName("currency");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text")
                        .HasColumnName("internalNotes");

                    b.Property<int>("Nights")
                        .HasColumnType("integer")
                        .HasColumnName("nights");

                    b.Property<decimal>("PricePerNightSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricePerNightSnapshot");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomId");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("text")
                        .HasColumnName("specialRequests");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalPrice");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("iX_reservations_clientId");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("iX_reservations_reference");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("iX_reservations_roomId");

                    b.ToTable("reservations", t =>
                        {
                            t.HasCheckConstraint("ck_checkOutAfterCheckIn", "\"checkOutDate\" > \"checkInDate\"");
                        });
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CapacityAdults")
                        .HasColumnType("integer")
                        .HasColumnName("capacityAdults");

                    b.Property<int>("CapacityChildren")
                        .HasColumnType("integer")
                        .HasColumnName("capacityChildren");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("descriptionEn");

                    b.Property<string>("DescriptionFr")
                        .HasColumnType("text")
                        .HasColumnName("descriptionFr");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("isFeatured");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameEn");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nameFr");

                    b.Property<decimal?>("PricePerMonth")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricePerMonth");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricePerNight");

                    b.Property<decimal?>("PricePerWeek")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricePerWeek");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roomNumber");

                    b.Property<decimal?>("SizeSqm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("sizeSqm");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("iX_rooms_roomNumber");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomId");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("iX_roomBlocks_roomId");

                    b.ToTable("roomBlocks", t =>
                        {
                            t.HasCheckConstraint("ck_blockEndAfterStart", "\"endDate\" > \"startDate\"");
                        });
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AltTextEn")
                        .HasColumnType("text")
                        .HasColumnName("altTextEn");

                    b.Property<string>("AltTextFr")
                        .HasColumnType("text")
                        .HasColumnName("altTextFr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filePath");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("isCover");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("roomId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("iX_roomImages_roomId");

                    b.ToTable("roomImages");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastLoginAt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("staff")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("iX_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_roomAmenities_Amenities_amenitiesId");

                    b.HasOne("Juweirat.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_roomAmenities_Rooms_roomsId");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_payments_Reservations_reservationId");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_reservations_clients_clientId");

                    b.HasOne("Juweirat.Domain.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_reservations_Rooms_roomId");

                    b.Navigation("Client");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomBlock", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Room", "Room")
                        .WithMany("Blocks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_roomBlocks_rooms_roomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.RoomImage", b =>
                {
                    b.HasOne("Juweirat.Domain.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_roomImages_rooms_roomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Juweirat.Domain.Entities.Room", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Images");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
