-- =============================================================================
-- Rattrapage des migrations non appliquées en production
-- =============================================================================
-- Contexte : suite à un conflit de timestamp sur 20260818000001 (2 migrations
-- avec le même prefix : AddCategoryImages et AddGarantieToReservation) et à
-- l'absence des fichiers .Designer.cs, EF Core s'est arrêté après
-- AddCategoryImages. Les 5 migrations suivantes ne sont donc jamais entrées
-- en base — d'où les erreurs 500 : relation "companies", "prestationsAnnexes",
-- "ventesDirectes" does not exist.
--
-- Ce script :
--   1) Crée (idempotent) toutes les tables/colonnes/index manquantes
--   2) Insère les 5 lignes dans __EFMigrationsHistory pour synchroniser
--
-- Peut être ré-exécuté sans effet néfaste. À lancer une seule fois en prod.
-- =============================================================================

BEGIN;

-- ─── 20260818000001_AddGarantieToReservation ──────────────────────────────
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='reservations' AND column_name='garantieType') THEN
        ALTER TABLE reservations ADD COLUMN "garantieType"        text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='reservations' AND column_name='garantieMontantCash') THEN
        ALTER TABLE reservations ADD COLUMN "garantieMontantCash" numeric(10,2);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='reservations' AND column_name='carteNom') THEN
        ALTER TABLE reservations ADD COLUMN "carteNom"            text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='reservations' AND column_name='carteSuffix') THEN
        ALTER TABLE reservations ADD COLUMN "carteSuffix"         character varying(4);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='reservations' AND column_name='carteExpiration') THEN
        ALTER TABLE reservations ADD COLUMN "carteExpiration"     character varying(7);
    END IF;
END $$;

-- ─── 20260818000002_AddPrestationsAnnexes ─────────────────────────────────
CREATE TABLE IF NOT EXISTS "prestationsAnnexes" (
    id           bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nameFr"     text           NOT NULL,
    "nameEn"     text           NOT NULL,
    icon         text,
    mode         text           NOT NULL DEFAULT 'ParPersonneParNuit',
    "prixInclus" numeric(10,2)  NOT NULL,
    "prixSeule"  numeric(10,2)  NOT NULL,
    "isActive"   boolean        NOT NULL DEFAULT TRUE,
    "sortOrder"  integer        NOT NULL DEFAULT 0,
    "createdAt"  timestamptz    NOT NULL DEFAULT NOW(),
    "updatedAt"  timestamptz    NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "reservationPrestations" (
    id                      bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "reservationId"         bigint         NOT NULL,
    "prestationId"          bigint         NOT NULL,
    quantite                integer        NOT NULL,
    "prixUnitaireSnapshot"  numeric(10,2)  NOT NULL,
    "totalLigne"            numeric(10,2)  NOT NULL,
    CONSTRAINT "FK_reservationPrestations_reservations_reservationId"
        FOREIGN KEY ("reservationId") REFERENCES reservations(id) ON DELETE CASCADE,
    CONSTRAINT "FK_reservationPrestations_prestationsAnnexes_prestationId"
        FOREIGN KEY ("prestationId") REFERENCES "prestationsAnnexes"(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_reservationPrestations_reservationId" ON "reservationPrestations" ("reservationId");
CREATE INDEX IF NOT EXISTS "IX_reservationPrestations_prestationId"  ON "reservationPrestations" ("prestationId");

-- ─── 20260818000003_AddVentesDirectes ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS "ventesDirectes" (
    id                      bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "prestationId"          bigint         NOT NULL,
    "clientId"              bigint,
    "clientNom"             text,
    "folioId"               bigint,
    quantite                integer        NOT NULL DEFAULT 1,
    "prixUnitaireSnapshot"  numeric(10,2)  NOT NULL,
    total                   numeric(10,2)  NOT NULL,
    mode                    text           NOT NULL DEFAULT 'Encaissement',
    "paymentMethod"         text,
    notes                   text,
    "createdAt"             timestamptz    NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_ventesDirectes_prestationsAnnexes_prestationId"
        FOREIGN KEY ("prestationId") REFERENCES "prestationsAnnexes"(id) ON DELETE RESTRICT,
    CONSTRAINT "FK_ventesDirectes_clients_clientId"
        FOREIGN KEY ("clientId")     REFERENCES clients(id)             ON DELETE RESTRICT,
    CONSTRAINT "FK_ventesDirectes_folios_folioId"
        FOREIGN KEY ("folioId")      REFERENCES folios(id)              ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_ventesDirectes_prestationId" ON "ventesDirectes" ("prestationId");
CREATE INDEX IF NOT EXISTS "IX_ventesDirectes_clientId"    ON "ventesDirectes" ("clientId");
CREATE INDEX IF NOT EXISTS "IX_ventesDirectes_folioId"     ON "ventesDirectes" ("folioId");
CREATE INDEX IF NOT EXISTS "IX_ventesDirectes_createdAt"   ON "ventesDirectes" ("createdAt");

-- ─── 20260818000004_AddCompanies ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS companies (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             text        NOT NULL,
    "responsableNom" text,
    phone            text,
    email            text,
    adresse          text,
    ville            text,
    notes            text,
    "isActive"       boolean     NOT NULL DEFAULT TRUE,
    "createdAt"      timestamptz NOT NULL DEFAULT NOW(),
    "updatedAt"      timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "companyTarifs" (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "companyId"  bigint      NOT NULL,
    "categoryId" bigint      NOT NULL,
    "tarifNuit"  integer     NOT NULL,
    "tarifN15"   integer     NOT NULL,
    "tarifN30"   integer     NOT NULL,
    "createdAt"  timestamptz NOT NULL DEFAULT NOW(),
    "updatedAt"  timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_companyTarifs_companies_companyId"
        FOREIGN KEY ("companyId")  REFERENCES companies(id)      ON DELETE CASCADE,
    CONSTRAINT "FK_companyTarifs_roomCategories_categoryId"
        FOREIGN KEY ("categoryId") REFERENCES "roomCategories"(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_companyTarifs_companyId_categoryId" ON "companyTarifs" ("companyId", "categoryId");
CREATE INDEX IF NOT EXISTS "IX_companyTarifs_categoryId" ON "companyTarifs" ("categoryId");

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clients' AND column_name='companyId') THEN
        ALTER TABLE clients ADD COLUMN "companyId" bigint;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_clients_companies_companyId') THEN
        ALTER TABLE clients ADD CONSTRAINT "FK_clients_companies_companyId"
            FOREIGN KEY ("companyId") REFERENCES companies(id) ON DELETE SET NULL;
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS "IX_clients_companyId" ON clients ("companyId");

-- ─── 20260818000005_AddMaintenanceStaff ───────────────────────────────────
CREATE TABLE IF NOT EXISTS "maintenanceCategories" (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text        NOT NULL,
    "isActive"  boolean     NOT NULL DEFAULT TRUE,
    "createdAt" timestamptz NOT NULL DEFAULT NOW(),
    "updatedAt" timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "maintenanceStaff" (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "categoryId" bigint      NOT NULL,
    "firstName"  text        NOT NULL,
    "lastName"   text        NOT NULL,
    phone        text,
    "isActive"   boolean     NOT NULL DEFAULT TRUE,
    "createdAt"  timestamptz NOT NULL DEFAULT NOW(),
    "updatedAt"  timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_maintenanceStaff_maintenanceCategories_categoryId"
        FOREIGN KEY ("categoryId") REFERENCES "maintenanceCategories"(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_maintenanceStaff_categoryId" ON "maintenanceStaff" ("categoryId");

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='maintenanceTickets') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='maintenanceTickets' AND column_name='staffId') THEN
            ALTER TABLE "maintenanceTickets" ADD COLUMN "staffId" bigint;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_maintenanceTickets_maintenanceStaff_staffId') THEN
            ALTER TABLE "maintenanceTickets" ADD CONSTRAINT "FK_maintenanceTickets_maintenanceStaff_staffId"
                FOREIGN KEY ("staffId") REFERENCES "maintenanceStaff"(id) ON DELETE SET NULL;
        END IF;
        CREATE INDEX IF NOT EXISTS "IX_maintenanceTickets_staffId" ON "maintenanceTickets" ("staffId");
    ELSE
        RAISE NOTICE '[CATCHUP] Table maintenanceTickets absente — colonne staffId non ajoutée.';
    END IF;
END $$;

-- ─── Marquer les 5 migrations comme appliquées dans l'historique EF Core ──
-- ProductVersion aligné sur les autres entrées récentes (9.0.2 ou 10.0.10).
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260818000001_AddGarantieToReservation', '10.0.10'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818000001_AddGarantieToReservation');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260818000002_AddPrestationsAnnexes',     '10.0.10'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818000002_AddPrestationsAnnexes');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260818000003_AddVentesDirectes',         '10.0.10'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818000003_AddVentesDirectes');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260818000004_AddCompanies',              '10.0.10'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818000004_AddCompanies');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260818000005_AddMaintenanceStaff',       '10.0.10'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260818000005_AddMaintenanceStaff');

-- ─── Récap ────────────────────────────────────────────────────────────────
DO $$
DECLARE
    v_hist_count int;
    v_tables_ok  int;
BEGIN
    SELECT COUNT(*) INTO v_hist_count FROM "__EFMigrationsHistory";
    SELECT COUNT(*) INTO v_tables_ok
      FROM information_schema.tables
     WHERE table_name IN ('companies','companyTarifs','prestationsAnnexes','reservationPrestations','ventesDirectes','maintenanceCategories','maintenanceStaff');

    RAISE NOTICE '';
    RAISE NOTICE '════════════════════════════════════════';
    RAISE NOTICE '  Migrations en historique : %', v_hist_count;
    RAISE NOTICE '  Tables neuves présentes  : % / 7', v_tables_ok;
    RAISE NOTICE '════════════════════════════════════════';
    RAISE NOTICE '';
    RAISE NOTICE '✅ Prochain redémarrage de l''API : plus d''erreur 500 sur';
    RAISE NOTICE '   /api/companies, /api/prestations, /api/ventes-directes';
    RAISE NOTICE '';
    RAISE NOTICE '➡️  Enchaîne ensuite avec seed_companies_2026.sql';
END $$;

COMMIT;
